### ISSUE TITLE
Waiting for a README and bug fixing

### ISSUE THREAD

**Issue by lntzm** [K-Nick/MS-DETR#1]
Hi, would you like to add a README to tell how to build the environment and run the code?
Also, It seems that there are many bugs in the code. I correct some import error in `kn_util`, but I don't find the definition of the function `build_tsvg_parser` at any location when running many configs.
```
Traceback (most recent call last):
  File "/MS-DETR/main.py", line 183, in <module>
    main(args)
  File "/MS-DETR/main.py", line 97, in main
    train_loader = build_dataloader(cfg, split="train")
  File "/MS-DETR/data/build.py", line 20, in build_dataloader
    datapipe = build_datapipe(cfg, split=split)
  File "/MS-DETR/data/build.py", line 11, in build_datapipe
    return registry.build_datapipe(cfg.data.datapipe, cfg=cfg, split=split)
  File "/MS-DETR/kn_util/basic/registry.py", line 98, in build_datapipe
    return cls.build(_name, "datapipe", **kwargs)
  File "/MS-DETR/kn_util/basic/registry.py", line 53, in build
    return cls.mapping[_domain][_name](**kwargs)
  File "/MS-DETR/models/ms_temporal_detr/datapipe.py", line 133, in build_datapipe_mst_detr_v2
    dataset_dp = build_tsvg_parser(cfg, split=split)
NameError: name 'build_tsvg_parser' is not defined
```
 Looking forward to your update and thx!

**Comment by jingwangsg** [comment]
necessary env includes
- pytorch 2.0+
- torchtext
- torchvision
- torchmetrics
- torchdata 0.6.0
- omegaconf
e.t.c.

I've added a requirement.txt into the repo.

build_tsvg_parser should be build_nlvl_parser now.

I'm currently occupied by a new project right now. As readme said, I will get back and reorganize the code into a bug-free and readable one. Thank you for your understanding:)

**Comment by lntzm** [comment]
Thanks for your reply!
